// Poster thumbnails hotlinked from Wikipedia (pageimages API).
// Regenerate with scripts/fetch-covers.mjs if titles change.
const COVERS = {
  "Hawkeye": "https://upload.wikimedia.org/wikipedia/en/7/7a/Hawkeye_%28miniseries%29_logo.png",
  "Wonder Man": "https://upload.wikimedia.org/wikipedia/en/b/bd/Wonder_Man_%28TV_series%29_logo.png",
  "Iron Man": "https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg",
  "The Incredible Hulk": "https://upload.wikimedia.org/wikipedia/en/f/f0/The_Incredible_Hulk_%28film%29_poster.jpg",
  "Iron Man 2": "https://upload.wikimedia.org/wikipedia/en/e/ed/Iron_Man_2_poster.jpg",
  "Thor": "https://upload.wikimedia.org/wikipedia/en/9/95/Thor_%28film%29_poster.jpg",
  "Captain America: The First Avenger": "https://upload.wikimedia.org/wikipedia/en/3/37/Captain_America_The_First_Avenger_poster.jpg",
  "The Avengers": "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg",
  "Iron Man 3": "https://upload.wikimedia.org/wikipedia/en/1/19/Iron_Man_3_poster.jpg",
  "Thor: The Dark World": "https://upload.wikimedia.org/wikipedia/en/7/7f/Thor_The_Dark_World_poster.jpg",
  "Captain America: The Winter Soldier": "https://upload.wikimedia.org/wikipedia/en/9/9e/Captain_America_The_Winter_Soldier_poster.jpg",
  "Guardians of the Galaxy": "https://upload.wikimedia.org/wikipedia/en/3/33/Guardians_of_the_Galaxy_%28film%29_poster.jpg",
  "Avengers: Age of Ultron": "https://upload.wikimedia.org/wikipedia/en/f/ff/Avengers_Age_of_Ultron_poster.jpg",
  "Ant-Man": "https://upload.wikimedia.org/wikipedia/en/1/12/Ant-Man_%28film%29_poster.jpg",
  "Captain America: Civil War": "https://upload.wikimedia.org/wikipedia/en/5/53/Captain_America_Civil_War_poster.jpg",
  "Doctor Strange": "https://upload.wikimedia.org/wikipedia/en/a/a1/Doctor_Strange_%282016_film%29_poster.jpg",
  "Guardians of the Galaxy Vol. 2": "https://upload.wikimedia.org/wikipedia/en/3/32/Guardians_of_the_Galaxy_Vol._2_poster.jpg",
  "Spider-Man: Homecoming": "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg",
  "Thor: Ragnarok": "https://upload.wikimedia.org/wikipedia/en/7/7d/Thor_Ragnarok_poster.jpg",
  "Black Panther": "https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg",
  "Avengers: Infinity War": "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
  "Ant-Man and the Wasp": "https://upload.wikimedia.org/wikipedia/en/2/2c/Ant-Man_and_the_Wasp_poster.jpg",
  "Captain Marvel": "https://upload.wikimedia.org/wikipedia/en/4/4e/Captain_Marvel_%28film%29_poster.jpg",
  "Avengers: Endgame": "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
  "Spider-Man: Far From Home": "https://upload.wikimedia.org/wikipedia/en/b/bd/Spider-Man_Far_From_Home_poster.jpg",
  "Black Widow": "https://upload.wikimedia.org/wikipedia/en/e/e9/Black_Widow_%282021_film%29_poster.jpg",
  "Shang-Chi and The Legend of the Ten Rings": "https://upload.wikimedia.org/wikipedia/en/7/74/Shang-Chi_and_the_Legend_of_the_Ten_Rings_poster.jpeg",
  "Eternals": "https://upload.wikimedia.org/wikipedia/en/9/9b/Eternals_%28film%29_poster.jpeg",
  "Spider-Man: No Way Home": "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
  "Doctor Strange in the Multiverse of Madness": "https://upload.wikimedia.org/wikipedia/en/1/17/Doctor_Strange_in_the_Multiverse_of_Madness_poster.jpg",
  "Thor: Love and Thunder": "https://upload.wikimedia.org/wikipedia/en/8/88/Thor_Love_and_Thunder_poster.jpeg",
  "Black Panther: Wakanda Forever": "https://upload.wikimedia.org/wikipedia/en/3/3b/Black_Panther_Wakanda_Forever_poster.jpg",
  "Ant-Man and the Wasp: Quantumania": "https://upload.wikimedia.org/wikipedia/en/3/30/Ant-Man_and_the_Wasp_Quantumania_poster.jpg",
  "Guardians of the Galaxy Vol. 3": "https://upload.wikimedia.org/wikipedia/en/7/74/Guardians_of_the_Galaxy_Vol._3_poster.jpg",
  "The Marvels": "https://upload.wikimedia.org/wikipedia/en/7/7a/The_Marvels_poster.jpg",
  "Deadpool and Wolverine": "https://upload.wikimedia.org/wikipedia/en/4/4c/Deadpool_%26_Wolverine_poster.jpg",
  "Captain America: Brave New World": "https://upload.wikimedia.org/wikipedia/en/a/a4/Captain_America_Brave_New_World_poster.jpg",
  "Thunderbolts*": "https://upload.wikimedia.org/wikipedia/en/9/90/Thunderbolts%2A_poster.jpg",
  "The Fantastic Four: First Steps": "https://upload.wikimedia.org/wikipedia/en/1/13/The_Fantastic_Four_First_Steps_poster.jpg",
  "Spider-Man: Brand New Day": "https://upload.wikimedia.org/wikipedia/en/9/9a/Spider-Man_Brand_New_Day_poster.jpg",
  "WandaVision": "https://upload.wikimedia.org/wikipedia/en/2/20/WandaVision_logo.png",
  "The Falcon and the Winter Soldier": "https://upload.wikimedia.org/wikipedia/en/9/9a/The_Falcon_and_the_Winter_Soldier_logo.png",
  "Loki Season 1": "https://upload.wikimedia.org/wikipedia/en/c/c9/Loki_season_1_poster.jpeg",
  "What If Season 1": "https://upload.wikimedia.org/wikipedia/en/9/91/What_If...%3F_season_1_poster.jpeg",
  "Moon Knight": "https://upload.wikimedia.org/wikipedia/en/a/a8/Moon_Knight_%28miniseries%29_logo.jpg",
  "Ms. Marvel": "https://upload.wikimedia.org/wikipedia/en/a/ac/Ms._Marvel_%28miniseries%29_logo.jpg",
  "I Am Groot Season 1": "https://upload.wikimedia.org/wikipedia/en/f/f7/I_Am_Groot_logo.jpeg",
  "She-Hulk: Attorney at Law": "https://upload.wikimedia.org/wikipedia/en/3/32/She-Hulk_Attorney_at_Law_logo.jpg",
  "Werewolf By Night": "https://upload.wikimedia.org/wikipedia/en/0/06/Werewolf_by_Night_%28TV_special%29_poster.jpg",
  "Guardians Holiday Special": "https://upload.wikimedia.org/wikipedia/en/e/e3/The_Guardians_of_the_Galaxy_Holiday_Special_poster.jpg",
  "Secret Invasion": "https://upload.wikimedia.org/wikipedia/en/9/91/Secret_Invasion_%28miniseries%29_logo.jpg",
  "I Am Groot Season 2": "https://upload.wikimedia.org/wikipedia/en/f/f7/I_Am_Groot_logo.jpeg",
  "Loki Season 2": "https://upload.wikimedia.org/wikipedia/en/4/4b/Loki_season_2_poster.jpg",
  "What If Season 2": "https://upload.wikimedia.org/wikipedia/en/b/b4/What_If...%3F_season_2_poster.jpeg",
  "Echo": "https://upload.wikimedia.org/wikipedia/en/9/99/Echo_%28miniseries%29_logo.jpg",
  "Ironheart": "https://upload.wikimedia.org/wikipedia/en/e/e9/Ironheart_%28miniseries%29_logo.png",
  "Agatha All Along": "https://upload.wikimedia.org/wikipedia/en/7/70/Agatha_All_Along_logo.jpg",
  "What If Season 3": "https://upload.wikimedia.org/wikipedia/en/b/ba/What_If...%3F_season_3_poster.jpeg",
  "Daredevil: Born Again Season 1": "https://upload.wikimedia.org/wikipedia/en/d/d9/Daredevil_Born_Again_logo.jpeg",
  "Eyes of Wakanda": "https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Eyes_of_Wakanda_logo.jpg/500px-Eyes_of_Wakanda_logo.jpg",
  "Marvel Zombies": "https://upload.wikimedia.org/wikipedia/en/1/1a/Marvel_Zombies_%28TV_series%29_logo.png",
  "Daredevil: Born Again Season 2": "https://upload.wikimedia.org/wikipedia/en/d/d9/Daredevil_Born_Again_logo.jpeg",
  "X-Men '97 Season 1": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/X-Men_%2797_logo.png/500px-X-Men_%2797_logo.png",
  "Your Friendly Neighborhood Spider-Man": "https://upload.wikimedia.org/wikipedia/en/a/a8/Your_Friendly_Neighborhood_Spider-Man_logo.png",
  "Agents of SHIELD Season 1": "https://upload.wikimedia.org/wikipedia/en/5/53/Agents_of_S.H.I.E.L.D._season_1_poster.jpeg",
  "Agents of SHIELD Season 2": "https://upload.wikimedia.org/wikipedia/en/5/5e/Agents_of_S.H.I.E.L.D._season_2_poster.jpg",
  "Agents of SHIELD Season 3": "https://upload.wikimedia.org/wikipedia/en/b/ba/Agents_of_S.H.I.E.L.D._season_3_poster.jpg",
  "Agents of SHIELD Season 4": "https://upload.wikimedia.org/wikipedia/en/3/39/Agents_of_S.H.I.E.L.D._season_4_poster.jpg",
  "Agents of SHIELD Season 5": "https://upload.wikimedia.org/wikipedia/en/5/5f/Agents_of_S.H.I.E.L.D._season_5_poster.jpg",
  "Agents of SHIELD Season 6": "https://upload.wikimedia.org/wikipedia/en/a/a1/Agents_of_S.H.I.E.L.D._season_6_poster.jpg",
  "Agents of SHIELD Season 7": "https://upload.wikimedia.org/wikipedia/en/f/f2/Agents_of_S.H.I.E.L.D._season_7_poster.jpg",
  "Agent Carter Season 1": "https://upload.wikimedia.org/wikipedia/en/e/eb/Agent_Carter_season_1_poster.jpg",
  "Agent Carter Season 2": "https://upload.wikimedia.org/wikipedia/en/e/e2/Agent_Carter_season_2_poster.jpg",
  "Daredevil Season 1": "https://upload.wikimedia.org/wikipedia/en/1/1b/Daredevil_season_1_poster.jpg",
  "Daredevil Season 2": "https://upload.wikimedia.org/wikipedia/en/5/5f/Daredevil_season_2_poster.jpg",
  "Daredevil Season 3": "https://upload.wikimedia.org/wikipedia/en/1/19/Daredevil_season_3_poster.jpg",
  "Jessica Jones Season 1": "https://upload.wikimedia.org/wikipedia/en/c/c1/Jessica_Jones_season_1_poster.jpg",
  "Jessica Jones Season 2": "https://upload.wikimedia.org/wikipedia/en/f/f0/Jessica_Jones_season_2_poster.jpg",
  "Jessica Jones Season 3": "https://upload.wikimedia.org/wikipedia/en/3/3e/Jessica_Jones_season_3_poster.jpg",
  "Luke Cage Season 1": "https://upload.wikimedia.org/wikipedia/en/3/37/Luke_Cage_season_1_poster.jpeg",
  "Luke Cage Season 2": "https://upload.wikimedia.org/wikipedia/en/d/d3/Luke_Cage_season_2_poster.jpg",
  "Iron Fist Season 1": "https://upload.wikimedia.org/wikipedia/en/e/ef/Iron_Fist_season_1_poster.jpg",
  "Iron Fist Season 2": "https://upload.wikimedia.org/wikipedia/en/c/c1/Iron_Fist_season_2_poster.jpg",
  "The Defenders Season 1": "https://upload.wikimedia.org/wikipedia/en/7/72/The_Defenders_%28miniseries%29_logo.jpg",
  "Inhumans Season 1": "https://upload.wikimedia.org/wikipedia/en/2/2f/Inhumans_%28TV_series%29_logo.jpg",
  "The Punisher Season 1": "https://upload.wikimedia.org/wikipedia/en/2/21/The_Punisher_season_1_poster.jpg",
  "The Punisher Season 2": "https://upload.wikimedia.org/wikipedia/en/1/17/The_Punisher_season_2_poster.jpg",
  "Runaways Season 1": "https://upload.wikimedia.org/wikipedia/en/2/2d/Runaways_%28TV_series%29_logo.jpg",
  "Runaways Season 2": "https://upload.wikimedia.org/wikipedia/en/2/2d/Runaways_%28TV_series%29_logo.jpg",
  "Runaways Season 3": "https://upload.wikimedia.org/wikipedia/en/2/2d/Runaways_%28TV_series%29_logo.jpg",
  "Cloak & Dagger Season 1": "https://upload.wikimedia.org/wikipedia/en/2/28/Cloak_%26_Dagger_season_1_poster.jpg",
  "Cloak & Dagger Season 2": "https://upload.wikimedia.org/wikipedia/en/7/72/Cloak_%26_Dagger_season_2_poster.jpg"
};
