// Data synced from the "Marvel Ranked" Google Sheet by scripts/fetch-sheet.mjs.
// Ratings are 0–10. Release-order rating columns are treated as canonical.
// Phase and year are not in the sheet: the script carries them over per title,
// so fill them in here whenever it reports a new one.

const MOVIES = [
  { title: "Iron Man", rating: 8, phase: 1, year: 2008, release: 0 },
  { title: "The Incredible Hulk", rating: 2, phase: 1, year: 2008, release: 1 },
  { title: "Iron Man 2", rating: 3, phase: 1, year: 2010, release: 2 },
  { title: "Thor", rating: 3, phase: 1, year: 2011, release: 3 },
  { title: "Captain America: The First Avenger", rating: 7, phase: 1, year: 2011, release: 4 },
  { title: "The Avengers", rating: 9, phase: 1, year: 2012, release: 5 },
  { title: "Iron Man 3", rating: 4, phase: 2, year: 2013, release: 6 },
  { title: "Thor: The Dark World", rating: 1, phase: 2, year: 2013, release: 7 },
  { title: "Captain America: The Winter Soldier", rating: 9, phase: 2, year: 2014, release: 8 },
  { title: "Guardians of the Galaxy", rating: 9, phase: 2, year: 2014, release: 9 },
  { title: "Avengers: Age of Ultron", rating: 6, phase: 2, year: 2015, release: 10 },
  { title: "Ant-Man", rating: 4, phase: 2, year: 2015, release: 11 },
  { title: "Captain America: Civil War", rating: 10, phase: 3, year: 2016, release: 12 },
  { title: "Doctor Strange", rating: 6, phase: 3, year: 2016, release: 13 },
  { title: "Guardians of the Galaxy Vol. 2", rating: 3, phase: 3, year: 2017, release: 14 },
  { title: "Spider-Man: Homecoming", rating: 6, phase: 3, year: 2017, release: 15 },
  { title: "Thor: Ragnarok", rating: 7, phase: 3, year: 2017, release: 16 },
  { title: "Black Panther", rating: 6, phase: 3, year: 2018, release: 17 },
  { title: "Avengers: Infinity War", rating: 10, phase: 3, year: 2018, release: 18 },
  { title: "Ant-Man and the Wasp", rating: 2, phase: 3, year: 2018, release: 19 },
  { title: "Captain Marvel", rating: 2, phase: 3, year: 2019, release: 20 },
  { title: "Avengers: Endgame", rating: 8, phase: 3, year: 2019, release: 21 },
  { title: "Spider-Man: Far From Home", rating: 5, phase: 3, year: 2019, release: 22 },
  { title: "Black Widow", rating: 2, phase: 4, year: 2021, release: 26 },
  { title: "Shang-Chi and The Legend of the Ten Rings", rating: 5, phase: 4, year: 2021, release: 28 },
  { title: "Eternals", rating: 3, phase: 4, year: 2021, release: 29 },
  { title: "Spider-Man: No Way Home", rating: 9, phase: 4, year: 2021, release: 31 },
  { title: "Doctor Strange in the Multiverse of Madness", rating: 4, phase: 4, year: 2022, release: 33 },
  { title: "Thor: Love and Thunder", rating: 0, phase: 4, year: 2022, release: 35 },
  { title: "Black Panther: Wakanda Forever", rating: 2, phase: 4, year: 2022, release: 39 },
  { title: "Ant-Man and the Wasp: Quantumania", rating: 1, phase: 5, year: 2023, release: 41 },
  { title: "Guardians of the Galaxy Vol. 3", rating: 7, phase: 5, year: 2023, release: 42 },
  { title: "The Marvels", rating: 0, phase: 5, year: 2023, release: 46 },
  { title: "Deadpool and Wolverine", rating: 4, phase: 5, year: 2024, release: 50 },
  { title: "Captain America: Brave New World", rating: 3, phase: 5, year: 2025, release: 54 },
  { title: "Thunderbolts*", rating: 7, phase: 5, year: 2025, release: 56 },
  { title: "The Fantastic Four: First Steps", rating: 5, phase: 6, year: 2025, release: 58 },
  { title: "Spider-Man: Brand New Day", rating: 8, phase: 6, year: 2026, release: 65 },
];

// Best → worst, from the "Overall" column of the sheet.
const MOVIE_RANK_ORDER = [
  "Captain America: Civil War",
  "Avengers: Infinity War",
  "Captain America: The Winter Soldier",
  "The Avengers",
  "Guardians of the Galaxy",
  "Spider-Man: No Way Home",
  "Avengers: Endgame",
  "Iron Man",
  "Spider-Man: Brand New Day",
  "Thor: Ragnarok",
  "Thunderbolts*",
  "Captain America: The First Avenger",
  "Guardians of the Galaxy Vol. 3",
  "Avengers: Age of Ultron",
  "Doctor Strange",
  "Black Panther",
  "Spider-Man: Homecoming",
  "Spider-Man: Far From Home",
  "Shang-Chi and The Legend of the Ten Rings",
  "The Fantastic Four: First Steps",
  "Doctor Strange in the Multiverse of Madness",
  "Ant-Man",
  "Iron Man 3",
  "Deadpool and Wolverine",
  "Guardians of the Galaxy Vol. 2",
  "Thor",
  "Captain America: Brave New World",
  "Iron Man 2",
  "Eternals",
  "The Incredible Hulk",
  "Ant-Man and the Wasp",
  "Black Widow",
  "Captain Marvel",
  "Black Panther: Wakanda Forever",
  "Thor: The Dark World",
  "Ant-Man and the Wasp: Quantumania",
  "The Marvels",
  "Thor: Love and Thunder",
];

const SHOWS = [
  { title: "WandaVision", rating: 6, phase: 4, year: 2021, release: 23 },
  { title: "The Falcon and the Winter Soldier", rating: 6, phase: 4, year: 2021, release: 24 },
  { title: "Loki Season 1", rating: 7, phase: 4, year: 2021, release: 25 },
  { title: "What If Season 1", rating: 4, phase: 4, year: 2021, release: 27 },
  { title: "Hawkeye", rating: 8, phase: 4, year: 2021, release: 30 },
  { title: "Moon Knight", rating: 9, phase: 4, year: 2022, release: 32 },
  { title: "Ms. Marvel", rating: 5, phase: 4, year: 2022, release: 34 },
  { title: "I Am Groot Season 1", rating: 3, phase: 4, year: 2022, release: 36 },
  { title: "She-Hulk: Attorney at Law", rating: 0, phase: 4, year: 2022, release: 37 },
  { title: "Werewolf By Night", rating: 5, phase: 4, year: 2022, release: 38 },
  { title: "Guardians Holiday Special", rating: 3, phase: 4, year: 2022, release: 40 },
  { title: "Secret Invasion", rating: 5, phase: 5, year: 2023, release: 43 },
  { title: "I Am Groot Season 2", rating: 2, phase: 5, year: 2023, release: 44 },
  { title: "Loki Season 2", rating: 10, phase: 5, year: 2023, release: 45 },
  { title: "What If Season 2", rating: 3, phase: 5, year: 2023, release: 47 },
  { title: "Echo", rating: 3, phase: 5, year: 2024, release: 48 },
  { title: "Agatha All Along", rating: 5, phase: 5, year: 2024, release: 51 },
  { title: "Ironheart", rating: 5, phase: 5, year: 2025, release: 57 },
  { title: "Wonder Man", rating: 6, phase: 6, year: 2026, release: 61 },
];

const SHOW_RANK_ORDER = [
  "Loki Season 2",
  "Moon Knight",
  "Hawkeye",
  "Loki Season 1",
  "Wonder Man",
  "WandaVision",
  "The Falcon and the Winter Soldier",
  "Werewolf By Night",
  "Agatha All Along",
  "Ironheart",
  "Ms. Marvel",
  "Secret Invasion",
  "What If Season 1",
  "Echo",
  "Guardians Holiday Special",
  "What If Season 2",
  "I Am Groot Season 1",
  "I Am Groot Season 2",
  "She-Hulk: Attorney at Law",
];

const UNWATCHED_SHOWS = [
  { title: "X-Men '97 Season 1", phase: 5, year: 2024, release: 49 },
  { title: "What If Season 3", phase: 5, year: 2024, release: 52 },
  { title: "Your Friendly Neighborhood Spider-Man", phase: 5, year: 2025, release: 53 },
  { title: "Daredevil: Born Again Season 1", phase: 5, year: 2025, release: 55 },
  { title: "Eyes of Wakanda", phase: 5, year: 2025, release: 59 },
  { title: "Marvel Zombies", phase: 5, year: 2025, release: 60 },
  { title: "Daredevil: Born Again Season 2", phase: 6, year: 2026, release: 62 },
  { title: "The Punisher: One Last Kill", phase: 6, year: 2026, release: 63 },
  { title: "X-Men '97 Season 2", phase: 6, year: 2026, release: 64 },
];

const UPCOMING = [
  "VisionQuest",
  "Avengers: Doomsday",
  "Daredevil: Born Again Season 3",
  "Avengers: Secret Wars",
  "Black Panther 3",
  "Ghost Rider",
  "Shang Chi 2",
  "X-Men",
  "Nova",
  "Deadpool 4",
  "Spider Man 5",
];

// Pre-Disney+ era shows (release order), parked on their own page until
// they get watched and ranked.
const LEGACY_SHOWS = [
  { title: "Agents of SHIELD Season 1", phase: 2 },
  { title: "Agents of SHIELD Season 2", phase: 2 },
  { title: "Agent Carter Season 1", phase: 2 },
  { title: "Daredevil Season 1", phase: 2 },
  { title: "Agents of SHIELD Season 3", phase: 3 },
  { title: "Jessica Jones Season 1", phase: 3 },
  { title: "Agent Carter Season 2", phase: 3 },
  { title: "Daredevil Season 2", phase: 3 },
  { title: "Agents of SHIELD Season 4", phase: 3 },
  { title: "Luke Cage Season 1", phase: 3 },
  { title: "Iron Fist Season 1", phase: 3 },
  { title: "The Defenders Season 1", phase: 3 },
  { title: "Inhumans Season 1", phase: 3 },
  { title: "The Punisher Season 1", phase: 3 },
  { title: "Runaways Season 1", phase: 3 },
  { title: "Agents of SHIELD Season 5", phase: 3 },
  { title: "Jessica Jones Season 2", phase: 3 },
  { title: "Cloak & Dagger Season 1", phase: 3 },
  { title: "Luke Cage Season 2", phase: 3 },
  { title: "Iron Fist Season 2", phase: 3 },
  { title: "Daredevil Season 3", phase: 3 },
  { title: "Runaways Season 2", phase: 3 },
  { title: "The Punisher Season 2", phase: 3 },
  { title: "Cloak & Dagger Season 2", phase: 3 },
  { title: "Agents of SHIELD Season 6", phase: 3 },
  { title: "Jessica Jones Season 3", phase: 3 },
  { title: "Runaways Season 3", phase: 3 },
  { title: "Agents of SHIELD Season 7", phase: 3 },
];

const FRANCHISES = [
  { name: "Avengers", ratings: [9, 6, 10, 8] },
  { name: "Captain America", ratings: [7, 9, 10, 4] },
  { name: "Thunderbolts*", ratings: [7] },
  { name: "Spider-Man", ratings: [6, 5, 9, 7] },
  { name: "Guardians of the Galaxy", ratings: [9, 3, 6] },
  { name: "Iron Man", ratings: [8, 3, 4] },
  { name: "Doctor Strange", ratings: [6, 4] },
  { name: "Shang-Chi", ratings: [5] },
  { name: "Fantastic Four", ratings: [5] },
  { name: "Black Panther", ratings: [6, 2] },
  { name: "Deadpool & Wolverine", ratings: [4] },
  { name: "Eternals", ratings: [3] },
  { name: "Thor", ratings: [3, 1, 7, 0] },
  { name: "Ant-Man", ratings: [4, 2, 1] },
  { name: "Hulk", ratings: [2] },
  { name: "Black Widow", ratings: [2] },
  { name: "Captain Marvel", ratings: [2, 1] },
];
