// Data synced from the "Marvel Ranked" Google Sheet by scripts/fetch-sheet.mjs.
// Ratings are 0–10. Release-order rating columns are treated as canonical.
// Phase and year are not in the sheet: the script carries them over per title,
// so fill them in here whenever it reports a new one.

const MOVIES = [
  { title: "Iron Man", rating: 8, phase: 1, year: 2008 },
  { title: "The Incredible Hulk", rating: 2, phase: 1, year: 2008 },
  { title: "Iron Man 2", rating: 3, phase: 1, year: 2010 },
  { title: "Thor", rating: 3, phase: 1, year: 2011 },
  { title: "Captain America: The First Avenger", rating: 7, phase: 1, year: 2011 },
  { title: "The Avengers", rating: 9, phase: 1, year: 2012 },
  { title: "Iron Man 3", rating: 4, phase: 2, year: 2013 },
  { title: "Thor: The Dark World", rating: 1, phase: 2, year: 2013 },
  { title: "Captain America: The Winter Soldier", rating: 9, phase: 2, year: 2014 },
  { title: "Guardians of the Galaxy", rating: 9, phase: 2, year: 2014 },
  { title: "Avengers: Age of Ultron", rating: 6, phase: 2, year: 2015 },
  { title: "Ant-Man", rating: 4, phase: 2, year: 2015 },
  { title: "Captain America: Civil War", rating: 10, phase: 3, year: 2016 },
  { title: "Doctor Strange", rating: 6, phase: 3, year: 2016 },
  { title: "Guardians of the Galaxy Vol. 2", rating: 3, phase: 3, year: 2017 },
  { title: "Spider-Man: Homecoming", rating: 6, phase: 3, year: 2017 },
  { title: "Thor: Ragnarok", rating: 7, phase: 3, year: 2017 },
  { title: "Black Panther", rating: 6, phase: 3, year: 2018 },
  { title: "Avengers: Infinity War", rating: 10, phase: 3, year: 2018 },
  { title: "Ant-Man and the Wasp", rating: 2, phase: 3, year: 2018 },
  { title: "Captain Marvel", rating: 2, phase: 3, year: 2019 },
  { title: "Avengers: Endgame", rating: 8, phase: 3, year: 2019 },
  { title: "Spider-Man: Far From Home", rating: 5, phase: 3, year: 2019 },
  { title: "Black Widow", rating: 2, phase: 4, year: 2021 },
  { title: "Shang-Chi and The Legend of the Ten Rings", rating: 5, phase: 4, year: 2021 },
  { title: "Eternals", rating: 3, phase: 4, year: 2021 },
  { title: "Spider-Man: No Way Home", rating: 9, phase: 4, year: 2021 },
  { title: "Doctor Strange in the Multiverse of Madness", rating: 4, phase: 4, year: 2022 },
  { title: "Thor: Love and Thunder", rating: 0, phase: 4, year: 2022 },
  { title: "Black Panther: Wakanda Forever", rating: 2, phase: 4, year: 2022 },
  { title: "Ant-Man and the Wasp: Quantumania", rating: 1, phase: 5, year: 2023 },
  { title: "Guardians of the Galaxy Vol. 3", rating: 6, phase: 5, year: 2023 },
  { title: "The Marvels", rating: 1, phase: 5, year: 2023 },
  { title: "Deadpool and Wolverine", rating: 4, phase: 5, year: 2024 },
  { title: "Captain America: Brave New World", rating: 4, phase: 5, year: 2025 },
  { title: "Thunderbolts*", rating: 7, phase: 5, year: 2025 },
  { title: "The Fantastic Four: First Steps", rating: 5, phase: 6, year: 2025 },
  { title: "Spider-Man: Brand New Day", rating: 7, phase: 6, year: 2026 },
];

// Best → worst, from the "Overall" column of the sheet.
const MOVIE_RANK_ORDER = [
  "Avengers: Infinity War",
  "Captain America: Civil War",
  "Captain America: The Winter Soldier",
  "The Avengers",
  "Guardians of the Galaxy",
  "Spider-Man: No Way Home",
  "Avengers: Endgame",
  "Iron Man",
  "Thor: Ragnarok",
  "Spider-Man: Brand New Day",
  "Thunderbolts*",
  "Captain America: The First Avenger",
  "Guardians of the Galaxy Vol. 3",
  "Avengers: Age of Ultron",
  "Doctor Strange",
  "Black Panther",
  "Spider-Man: Homecoming",
  "Spider-Man: Far From Home",
  "Shang-Chi and The Legend of the Ten Rings",
  "The Fantastic Four: First Steps",
  "Doctor Strange in the Multiverse of Madness",
  "Ant-Man",
  "Iron Man 3",
  "Captain America: Brave New World",
  "Deadpool and Wolverine",
  "Guardians of the Galaxy Vol. 2",
  "Thor",
  "Iron Man 2",
  "Eternals",
  "The Incredible Hulk",
  "Ant-Man and the Wasp",
  "Captain Marvel",
  "Black Widow",
  "Black Panther: Wakanda Forever",
  "Thor: The Dark World",
  "Ant-Man and the Wasp: Quantumania",
  "The Marvels",
  "Thor: Love and Thunder",
];

const SHOWS = [
  { title: "WandaVision", rating: 6, phase: 4, year: 2021 },
  { title: "The Falcon and the Winter Soldier", rating: 6, phase: 4, year: 2021 },
  { title: "Loki Season 1", rating: 7, phase: 4, year: 2021 },
  { title: "What If Season 1", rating: 4, phase: 4, year: 2021 },
  { title: "Hawkeye", rating: 8, phase: 4, year: 2021 },
  { title: "Moon Knight", rating: 9, phase: 4, year: 2022 },
  { title: "Ms. Marvel", rating: 5, phase: 4, year: 2022 },
  { title: "I Am Groot Season 1", rating: 3, phase: 4, year: 2022 },
  { title: "She-Hulk: Attorney at Law", rating: 0, phase: 4, year: 2022 },
  { title: "Werewolf By Night", rating: 5, phase: 4, year: 2022 },
  { title: "Guardians Holiday Special", rating: 3, phase: 4, year: 2022 },
  { title: "Secret Invasion", rating: 5, phase: 5, year: 2023 },
  { title: "I Am Groot Season 2", rating: 2, phase: 5, year: 2023 },
  { title: "Loki Season 2", rating: 10, phase: 5, year: 2023 },
  { title: "What If Season 2", rating: 3, phase: 5, year: 2023 },
  { title: "Echo", rating: 3, phase: 5, year: 2024 },
  { title: "Ironheart", rating: 5, phase: 5, year: 2025 },
  { title: "Wonder Man", rating: 6, phase: 6, year: 2026 },
];

const SHOW_RANK_ORDER = [
  "Loki Season 2",
  "Moon Knight",
  "Hawkeye",
  "Loki Season 1",
  "Wonder Man",
  "WandaVision",
  "The Falcon and the Winter Soldier",
  "Werewolf By Night",
  "Secret Invasion",
  "Ironheart",
  "Ms. Marvel",
  "What If Season 1",
  "Echo",
  "Guardians Holiday Special",
  "What If Season 2",
  "I Am Groot Season 1",
  "I Am Groot Season 2",
  "She-Hulk: Attorney at Law",
];

const UNWATCHED_SHOWS = [
  "Agatha All Along",
  "What If Season 3",
  "Daredevil: Born Again Season 1",
  "Eyes of Wakanda",
  "Marvel Zombies",
  "Daredevil: Born Again Season 2",
  "The Punisher: One Last Kill",
];

const UPCOMING = [
  "VisionQuest",
  "Avengers: Doomsday",
  "Daredevil: Born Again Season 3",
  "Avengers: Secret Wars",
  "Black Panther 3",
  "Ghost Rider",
  "X-Men",
  "Shang-Chi 2",
  "Nova",
  "Deadpool 4",
];

const FRANCHISES = [
  { name: "Avengers", ratings: [9, 6, 10, 8] },
  { name: "Captain America", ratings: [7, 9, 10, 4] },
  { name: "Thunderbolts*", ratings: [7] },
  { name: "Spider-Man", ratings: [6, 5, 9, 7] },
  { name: "Guardians of the Galaxy", ratings: [9, 3, 6] },
  { name: "Iron Man", ratings: [8, 3, 4] },
  { name: "Doctor Strange", ratings: [6, 4] },
  { name: "Shang-Chi", ratings: [5] },
  { name: "Fantastic Four", ratings: [5] },
  { name: "Black Panther", ratings: [6, 2] },
  { name: "Deadpool & Wolverine", ratings: [4] },
  { name: "Eternals", ratings: [3] },
  { name: "Thor", ratings: [3, 1, 7, 0] },
  { name: "Ant-Man", ratings: [4, 2, 1] },
  { name: "Hulk", ratings: [2] },
  { name: "Black Widow", ratings: [2] },
  { name: "Captain Marvel", ratings: [2, 1] },
];
